[build]
  command = "npm run production"
  publish = "dist"

[[redirects]]
  from = "/vimparanoobs"
  to = "https://leanpub.com/vimparanoobs/"
  status = 301

[[redirects]]
  from = "/posts/pensando-em-componentes-de-interface-com-exemplos-em-react/"
  to = "https://imasters.com.br/desenvolvimento/pensando-em-componentes-de-interface-com-exemplos-em-react"
  status = 301

[[redirects]]
  from = "/posts/mentoria-como-meio-de-apoio-%C3%A0-evolu%C3%A7%C3%A3o-dos-nossos-funcion%C3%A1rios/"
  to = "https://imasters.com.br/carreira-dev/mentoria-como-meio-de-apoio-evolucao-dos-nossos-funcionarios"
  status = 301