[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = ""
  to = ""
  status = 301

[[redirects]]
  from = ""
  to = ""
  status = 301

[[redirects]]
  from = ""
  to = ""
  status = 301
