name: Audit pull request
on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Audit Netlify deploy preview
      uses: jakejarvis/lighthouse-action@master
      with:
        netlify_site: 'https://deploy-preview-[[PR_NUMBER]]--sleepy-keller-922c66.netlify.app/'
    - uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
